"""add images field

Revision ID: 44100a3e18ff
Revises: 4972e10e1513
Create Date: 2025-11-21 17:33:32.465321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44100a3e18ff'
down_revision = '4972e10e1513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('opinion', schema=None) as batch_op:
        batch_op.drop_column('images')

    # ### end Alembic commands ###
